<?php
require_once __DIR__.'/eventos.php';
$events=getEvents(); $result=null;
if($_SERVER['REQUEST_METHOD']==='POST'){$result=registerParticipant((string)($_POST['name']??''),(string)($_POST['email']??''),(int)($_POST['event_id']??0),$events);}
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Sistema de Gestao de Eventos</title>
<style>:root{--p:#a42bca;--bg:#f7f2fb;--b:#e3d5e9}*{box-sizing:border-box}body{margin:0;background:var(--bg);font:16px Arial;color:#27212b}header{padding:34px 20px;background:linear-gradient(120deg,#70208b,var(--p));color:white}header div,main{width:min(1000px,calc(100% - 32px));margin:auto}h1{margin:0 0 8px}main{padding:30px 0}.events{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:15px}.card,form,.message{background:white;border:1px solid var(--b);border-radius:9px;padding:18px}.card h3{color:#7d239a}.meta{line-height:1.6;color:#665d6a}.status{font-weight:bold;color:#7d239a}form{display:grid;gap:13px;max-width:650px}label{font-weight:bold}input,select,button{width:100%;min-height:44px;padding:9px;border:1px solid var(--b);border-radius:6px}button{background:var(--p);color:white;border:0;font-weight:bold}.message{max-width:650px;margin-bottom:12px;color:#176b43}.error{color:#a62a2a}</style></head>
<body><header><div><h1>Sistema de Gestao de Eventos</h1><p>Eventos, inscricoes e vagas em um unico lugar.</p></div></header><main>
<h2>Eventos disponiveis</h2><section class="events"><?php foreach($events as $event):?><article class="card"><h3><?=htmlspecialchars($event['title'])?></h3><div class="meta"><?=htmlspecialchars($event['date'].' as '.$event['time'])?><br><?=$event['registered']?> de <?=$event['capacity']?> vagas<br><?=$event['price']>0?'R$ '.number_format($event['price'],2,',','.'):'Gratuito'?></div><p class="status"><?=eventAvailability($event)?></p></article><?php endforeach;?></section>
<h2>Realizar inscricao</h2><?php if($result!==null):?><div class="message <?=$result['success']?'':'error'?>"><?=htmlspecialchars($result['success']?$result['message']:implode(' ',$result['errors']))?></div><?php endif;?>
<form method="post"><div><label for="name">Nome</label><input id="name" name="name" required></div><div><label for="email">E-mail</label><input id="email" name="email" type="email" required></div><div><label for="event_id">Evento</label><select id="event_id" name="event_id" required><option value="">Selecione</option><?php foreach($events as $event):?><option value="<?=$event['id']?>"><?=htmlspecialchars($event['title'])?></option><?php endforeach;?></select></div><button>Confirmar inscricao</button></form>
</main></body></html>
